#- name: apt update && upgrade
#  tags:
#    - common
#  become: true
#  apt: 
#    upgrade: yes
#    update_cache: yes
#    cache_valid_time: 3600 # One hour


- name: Install core packages
  tags:
    - common
  become: true
  apt:
    name: "{{ core }}"
    state: present


- name: Create ~/ directories for dotfiles
  tags:
    - common
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ homedirs }}"


- name: Clone dotfiles bare repo
  tags:
    - common
  git:
    repo: 'https://github.com/crlxs/dotfiles'
    dest: "{{ home }}/.dotfiles"
    bare: true


- name: Checkout content into ~/ # Haven't managed to do it with git module.
  tags:
    - common
  shell:
    cmd: git --git-dir=$HOME/.dotfiles --work-tree=$HOME checkout


- name: Define dotfiles alias for current shell
  tags:
    - common
  shell:
    cmd: alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles --work-tee=$HOME'


- name: Set showUntrackedFiles flag to no locally
  tags:
    - common
  shell:
    cmd: git --git-dir=$HOME/.dotfiles --work-tree=$HOME config --local status.showUntrackedFiles no


- name: Change default shell to zsh
  tags:
    - common
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh


- name: nvim stable download
  tags:
    - common
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/stable/nvim.appimage"
    dest: "{{ home }}/.local/bin/nvim.appimage"
    mode: '0755'


- name: rename nvim.appimage to nvim
  tags:
    - common
  shell: mv $HOME/.local/bin/nvim.appimage $HOME/.local/bin/nvim


#- name: clean-up ~/
#  tags:
#    - common
# ADD DEBUG MESSAGE TO REMIND DELETION OF OLD DOTFILES IN ~/
