- name: apt update && upgrade
  tags:
    - common
  become: true
  apt: 
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600 # One hour
    

- name: install core packages
  tags:
    - common
  become: true
  apt:
    name: "{{ core }}" 
    state: present

- name: create ~/ directories for dotfiles
  tags:
    - common
  file:
    path: "{{ homedirs }}"
    state: directory

- name: dotfiles clone, checkout and setup
  tags:
    - common

- name: change default shell to zsh
  tags:
    - common

- name: clean-up ~/
  tags:
    - common
