#- name: apt update && upgrade
#  tags:
#    - common
#  become: true
#  apt: 
#    upgrade: yes
#    update_cache: yes
#    cache_valid_time: 3600 # One hour


- name: Install core packages
  tags:
    - common
  become: true
  apt:
    name: "{{ core }}"
    state: present


- name: Create ~/ directories for dotfiles
  tags:
    - common
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ homedirs }}"


- name: Clone dotfiles bare repo
  tags:
    - common
  git:
    repo: 'https://github.com/crlxs/dotfiles'
    dest: "{{ home }}/.dotfiles"
    bare: true

- name: Checkout dotfiles repo
  tags:
    - common
  git:
    repo: "{{ home }}/.dotfiles"
    dest: "{{ home }}"
    clone: false

#- name: change default shell to zsh
#  tags:
#    - common

#- name: clean-up ~/
#  tags:
#    - common
