
#- name: apt update && upgrade
#  tags:
#    - common
#  become: true
#  apt: 
#    upgrade: yes
#    update_cache: yes
#    cache_valid_time: 3600 # One hour


- name: Ensure ~/.ssh exists
  tags:
    - gitssh
  file:
    dest: "{{ home }}/.ssh"
    state: directory


- name: Install ssh key
  tags:
    - gitssh
  copy:
    src: "{{ source_key}}"
    dest: "{{ dest_key }}"


- name: Set authorized key from file
  tags:
    - gitssh
  authorized_key:
    user: "{{lookup('env', 'USER' )}}"
    state: present
    key: "{{ home }}/.ssh/id_rsa.pub"
